//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditlog
    {
        public int auditlogid { get; set; }
        public System.DateTime createdat { get; set; }
        public string details { get; set; }
        public int adminid { get; set; }
        public int userid { get; set; }
        public Nullable<int> actionid { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
