//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ratingid { get; set; }
        public int userid { get; set; }
        public int packageid { get; set; }
        public string rating1 { get; set; }
        public string complain { get; set; }
        public string complainstatus { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual User User { get; set; }
    }
}
