//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucherentry
    {
        public int voucherentryid { get; set; }
        public int voucherid { get; set; }
        public int userid { get; set; }
    
        public virtual User User { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
